nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: using the "epoll" event method
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: nginx/1.25.5
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: OS: Linux 6.10.14-linuxkit
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker processes
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 21
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 22
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 23
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 24
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 25
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 26
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 27
nginx-1  | 2025/09/11 11:40:36 [notice] 1#1: start worker process 28
db-1     | 
db-1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1     | 
db-1     | 2025-09-11 11:40:30.495 UTC [1] LOG:  starting PostgreSQL 16.10 (Debian 16.10-1.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1     | 2025-09-11 11:40:30.496 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2025-09-11 11:40:30.496 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2025-09-11 11:40:30.498 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2025-09-11 11:40:30.505 UTC [27] LOG:  database system was shut down at 2025-09-11 11:40:11 UTC
db-1     | 2025-09-11 11:40:30.512 UTC [1] LOG:  database system is ready to accept connections
db-1     | 2025-09-11 11:45:30.498 UTC [25] LOG:  checkpoint starting: time
db-1     | 2025-09-11 11:45:30.525 UTC [25] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.001 s, total=0.027 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1960628, redo lsn=0/19605F0
backend-1  | [2025-09-11 11:40:36 +0000] [1] [INFO] Starting gunicorn 23.0.0
backend-1  | [2025-09-11 11:40:36 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend-1  | [2025-09-11 11:40:36 +0000] [1] [INFO] Using worker: sync
backend-1  | [2025-09-11 11:40:36 +0000] [7] [INFO] Booting worker with pid: 7
backend-1  | [2025-09-11 12:40:36 +0100] [7] [ERROR] Exception in worker process
backend-1  | Traceback (most recent call last):
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
backend-1  |     import psycopg as Database
backend-1  | ModuleNotFoundError: No module named 'psycopg'
backend-1  | 
backend-1  | During handling of the above exception, another exception occurred:
backend-1  | 
backend-1  | Traceback (most recent call last):
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>
backend-1  |     import psycopg2 as Database
backend-1  | ModuleNotFoundError: No module named 'psycopg2'
backend-1  | 
backend-1  | During handling of the above exception, another exception occurred:
backend-1  | 
backend-1  | Traceback (most recent call last):
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
backend-1  |     worker.init_process()
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
backend-1  |     self.load_wsgi()
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
backend-1  |     self.wsgi = self.app.wsgi()
backend-1  |                 ^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
backend-1  |     self.callable = self.load()
backend-1  |                     ^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
backend-1  |     return self.load_wsgiapp()
backend-1  |            ^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
backend-1  |     return util.import_app(self.app_uri)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
backend-1  |     mod = importlib.import_module(module)
backend-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
backend-1  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
backend-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
backend-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
backend-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
backend-1  |   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
backend-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
backend-1  |   File "/app/project/wsgi.py", line 16, in <module>
backend-1  |     application = get_wsgi_application()
backend-1  |                   ^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
backend-1  |     django.setup(set_prefix=False)
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
backend-1  |     apps.populate(settings.INSTALLED_APPS)
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate
backend-1  |     app_config.import_models()
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models
backend-1  |     self.models_module = import_module(models_module_name)
backend-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
backend-1  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
backend-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
backend-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
backend-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
backend-1  |   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
backend-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/models.py", line 5, in <module>
backend-1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 43, in <module>
backend-1  |     class AbstractBaseUser(models.Model):
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 145, in __new__
backend-1  |     new_class.add_to_class("_meta", Options(meta, app_label))
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 373, in add_to_class
backend-1  |     value.contribute_to_class(cls, name)
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/options.py", line 238, in contribute_to_class
backend-1  |     self.db_table, connection.ops.max_name_length()
backend-1  |                    ^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/utils/connection.py", line 15, in __getattr__
backend-1  |     return getattr(self._connections[self._alias], item)
backend-1  |                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/utils/connection.py", line 62, in __getitem__
backend-1  |     conn = self.create_connection(alias)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 193, in create_connection
backend-1  |     backend = load_backend(db["ENGINE"])
backend-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 113, in load_backend
backend-1  |     return import_module("%s.base" % backend_name)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
backend-1  |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1  |   File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
backend-1  |     raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
backend-1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
backend-1  | [2025-09-11 12:40:36 +0100] [7] [INFO] Worker exiting (pid: 7)
backend-1  | [2025-09-11 11:40:36 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
backend-1  | [2025-09-11 11:40:36 +0000] [1] [ERROR] Shutting down: Master
backend-1  | [2025-09-11 11:40:36 +0000] [1] [ERROR] Reason: Worker failed to boot.
